FROM ruby:3.1.3 AS rails-env

WORKDIR /app

# Debugging command to list directory contents
RUN ls -la

COPY /api .

# Debugging command to list directory contents
RUN ls -la

RUN gem install rails bundler
RUN bundle install

ENTRYPOINT ["bundle", "exec"]
