apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/${{ github.repository_owner }}/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: 'redis://redis:6379/1'
            - name: DB_HOST
              value: db
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: password


