sidekiq:
  replicaCount: 1
  image:
    repository: ghcr.io/externaluseonly91/api
    tag: latest

service:
  name: sidekiq
  port: 8080

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
