name: casper

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  casper-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  


      - name: Build and Push Docker Images
        env:
          AWS_REGION: eu-central-1
          ECR_REPO_API: my-api-repo
          ECR_REPO_SPA: my-spa-repo
          ECR_REPO_NGINX: my-nginx-repo
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          ls -lrt
          pwd
          docker build -t $ECR_REPO_API:latest -f Dockerfile.rails .
          docker build -t $ECR_REPO_SPA:latest -f Dockerfile.react .
          docker build -t $ECR_REPO_NGINX:latest -f Dockerfile.nginx .

          # Authenticate Docker with ECR
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 846848477388.dkr.ecr.eu-central-1.amazonaws.com && echo "Docker login successful!"

          # Push images to ECR
          docker push $ECR_REPO_API:latest
          docker push $ECR_REPO_SPA:latest
          docker push $ECR_REPO_NGINX:latest
