name: casper

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  casper-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: kubectl
        run: kubectl get pods -A 
