name: casper

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  casper-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  

      - name: Set up Minikube
        run: |
          sudo apt-get install conntrack -y
          export PATH="/usr/sbin:$PATH"
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.28.0/crictl-v1.28.0-linux-amd64.tar.gz
          tar -xzvf crictl-v1.x.x-linux-amd64.tar.gz
          sudo mv crictl /usr/local/bin
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=none

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: kubectl
        run: kubectl get pods -A 
