name: tf-2

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

on:
 push:
   branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'tf-02-job'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v3
        with:
          repository: externaluseonly91/tf-2

          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
          
      - name: Check Azure CLI Version
        run: az version

      - name: Azure CLI Login
        uses: azure/login@v1
        with:         
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
          allow-no-subscriptions: true

          
      - name: Account show
        run: |
          az account show
          az account list --output table

      - name: print git workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.5  

      - name: 'Terraform init'
        id: init
        run: terraform init
          
